### ISSUE TITLE
pyroSAR not imported

### ISSUE THREAD

**Issue by getawork** [johntruckenbrodt/pyroSAR#100]
- which operating system are you using?  
e.g. Windows 10, Ubuntu 18.4, etc.
- which environment is pyroSAR running in?  
e.g. system-wide Python installation, Anaconda environment, virtual environment, etc.
- which version of pyroSAR are you using?  
one installed via pip or a clone of the GitHub repository?
-  which function of pyroSAR did you call with which parameters?  
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
- the full error message

**Comment by getawork** [comment]
After installation of pyroSAR, I have tried to import it for operational use but it pops up with the following error message. Is anybody who can help me?
`>>> import pyroSAR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\envs\forsent\lib\site-packages\pyroSAR\__init__.py", line 1, in <module>
    from .drivers import *
  File "C:\Anaconda2\envs\forsent\lib\site-packages\pyroSAR\drivers.py", line 45, in <module>
    from . import S1
  File "C:\Anaconda2\envs\forsent\lib\site-packages\pyroSAR\S1\__init__.py", line 3, in <module>
    from .auxil import OSV, removeGRDBorderNoise
  File "C:\Anaconda2\envs\forsent\lib\site-packages\pyroSAR\S1\auxil.py", line 17, in <module>
    from pyroSAR.examine import ExamineSnap
  File "C:\Anaconda2\envs\forsent\lib\site-packages\pyroSAR\examine.py", line 11, in <module>
    from pyroSAR._dev_config import ConfigHandler
  File "C:\Anaconda2\envs\forsent\lib\site-packages\pyroSAR\_dev_config.py", line 173
    class ConfigHandler(metaclass=Singleton):
                                 ^
SyntaxError: invalid syntax`

**Comment by johntruckenbrodt** [comment]
Hi,
please take your time to answer the questions in the template above so I can better understand this issue. It looks a lot like you are using Python2, which is no longer supported. If so, please update to Python3 and give me an update if the error persists.
Cheers,
John

**Comment by renedacosta** [comment]
Hi,
I'm also having an issue importing pyroSAR
I've tried python3.6 -> 3.8 all with same issue 
```python
>>>import pyroSAR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rene.da-costa\AppData\Local\Continuum\miniconda3\envs\dem\lib\site-packages\pyroSAR\__init__.py", line 1, in <module>
    from .drivers import *
  File "C:\Users\rene.da-costa\AppData\Local\Continuum\miniconda3\envs\dem\lib\site-packages\pyroSAR\drivers.py", line 42, in <module>
    from osgeo import gdal, osr
ModuleNotFoundError: No module named 'osgeo'
```
