### ISSUE TITLE
s1 processing with pyrosar generating occasional error messages: "Error: [NodeId: Read] Specified 'file'... ...tmp0.dim] does not exist"

### ISSUE THREAD

**Issue by DTMilodowski** [johntruckenbrodt/pyroSAR#129]
Hi there,

Firstly, thanks so much for developing this software! In general it works brilliantly, but when running geocode to process s1 scenes, for some scenes I am getting an error relating to a missing file from snap:

`Error: [NodeId: Read] Specified 'file' [/data/Sentinel-1/processed_to_dB/processed_no_filter/T30VUJ/2020/07/30/pyrosar/S1B__IW___D_20200730T065341_NR_Orb_TF_TC_dB/temp/S1B_IW_GRDH_1SDV_20200730T065341_20200730T065406_022697_02B13D_11A5_tmp0.dim] does not exist.`

The full error message is provided at the end of this post. I'm currently running the geocode function within a loop to batch process a bunch of sentinel 1 scenes downloaded from the ASF. Most iterations of the loop it works like a dream, but every now and then this error keeps cropping up. Based on the lines printed out to the console, it appears that when the error is thrown, it occurs consistently during the 'ThermalNoiseRemoval' step. Is this something that you have come across before? Any ideas how to fix it?

- which operating system are you using?  
**CentOS Linux release 8.3.2011**
- which environment is pyroSAR running in?  
**system-wide Python installation**
- which version of pyroSAR are you using?  
**clone of the GitHub repository**
-  which function of pyroSAR did you call with which parameters?  
**geocode**
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
**SNAP version 8**
- the full error message

`searching for new POE files
https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_POEORB&sentinel1__mission=S1B&validity_start__gte=2020-07-29T06:53:41&validity_stop__lte=2020-07-31T06:53:41
executing node sequences..
Subset
ThermalNoiseRemoval
Executing processing graph
 done.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: GDAL 3.0.0 found on system. JNI driver will be used.
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Internal GDAL 3.0.0 set to be used by SNAP.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
INFO: org.esa.s2tbx.dataio.gdal.GDALVersion: Internal GDAL 3.0.0 set to be used by SNAP.
org.esa.snap.core.gpf.graph.GraphException: [NodeId: Read] Specified 'file' [/data/Sentinel-1/processed_to_dB/processed_no_filter/T30VUJ/2020/07/30/pyrosar/S1B__IW___D_20200730T065341_NR_Orb_TF_TC_dB/temp/S1B_IW_GRDH_1SDV_20200730T065341_20200730T065406_022697_02B13D_11A5_tmp0.dim] does not exist.
	at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:79)
	at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:199)
	at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:182)
	at org.esa.snap.core.gpf.graph.GraphContext.initNodeContext(GraphContext.java:182)
	at org.esa.snap.core.gpf.graph.GraphContext.initOutput(GraphContext.java:166)
	at org.esa.snap.core.gpf.graph.GraphContext.<init>(GraphContext.java:85)
	at org.esa.snap.core.gpf.graph.GraphContext.<init>(GraphContext.java:58)
	at org.esa.snap.core.gpf.graph.GraphProcessor.executeGraph(GraphProcessor.java:118)
	at org.esa.snap.core.gpf.main.DefaultCommandLineContext.executeGraph(DefaultCommandLineContext.java:86)
	at org.esa.snap.core.gpf.main.CommandLineTool.executeGraph(CommandLineTool.java:547)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraph(CommandLineTool.java:391)
	at org.esa.snap.core.gpf.main.CommandLineTool.runGraphOrOperator(CommandLineTool.java:287)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:188)
	at org.esa.snap.core.gpf.main.CommandLineTool.run(CommandLineTool.java:121)
	at org.esa.snap.core.gpf.main.GPT.run(GPT.java:54)
	at org.esa.snap.core.gpf.main.GPT.main(GPT.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.esa.snap.runtime.Launcher.lambda$run$0(Launcher.java:55)
	at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
	at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
	at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.org.esa.snap.runtime.Launcher_gpt.main(Unknown Source)
Caused by: org.esa.snap.core.gpf.OperatorException: Specified 'file' [/data/Sentinel-1/processed_to_dB/processed_no_filter/T30VUJ/2020/07/30/pyrosar/S1B__IW___D_20200730T065341_NR_Orb_TF_TC_dB/temp/S1B_IW_GRDH_1SDV_20200730T065341_20200730T065406_022697_02B13D_11A5_tmp0.dim] does not exist.
	at org.esa.snap.core.gpf.common.ReadOp.initialize(ReadOp.java:113)
	at org.esa.snap.core.gpf.internal.OperatorContext.initializeOperator(OperatorContext.java:528)
	at org.esa.snap.core.gpf.internal.OperatorContext.getTargetProduct(OperatorContext.java:298)
	at org.esa.snap.core.gpf.Operator.getTargetProduct(Operator.java:385)
	at org.esa.snap.core.gpf.graph.NodeContext.initTargetProduct(NodeContext.java:77)
	... 30 more

Error: [NodeId: Read] Specified 'file' [/data/Sentinel-1/processed_to_dB/processed_no_filter/T30VUJ/2020/07/30/pyrosar/S1B__IW___D_20200730T065341_NR_Orb_TF_TC_dB/temp/S1B_IW_GRDH_1SDV_20200730T065341_20200730T065406_022697_02B13D_11A5_tmp0.dim] does not exist.`

Thanks again!

**Comment by DTMilodowski** [comment]
update...

This error only seems to occur when I use a shapefile to subset the scene. Running without a shapefile and the scene processes through to completion.

**Comment by konradmalik** [comment]
Not related but asking here: does the link for POE provided in the log (https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_POEORB&sentinel1__mission=S1B&validity_start__gte=2020-07-29T06:53:41&validity_stop__lte=2020-07-31T06:53:41) work for you? For me it seems that those servers are not responding since at least 2 days, thus I cannot process Sentinel-1 files using pyroSAR anymore.

**Comment by DTMilodowski** [comment]
Hi @konradmalik,

I am also unable to download POE files at the moment. I had a batch run processing over the weekend and they stopped going through midway through Monday. I'd hoped that the problem might have been resolved by now, but unfortunately not.

**Comment by DTMilodowski** [comment]
This relates to @konradmalik's question (unrelated to original issue)

Looks like there will be a fix coming to SNAP relating to the POE files. Hopefully soon! https://senbox.atlassian.net/browse/SITBX-842

**Comment by johntruckenbrodt** [comment]
Thanks a lot @DTMilodowski and @konradmalik for making me aware of this. I'll look into it tomorrow.

**Comment by johntruckenbrodt** [comment]
I just opened issue #131 for the OSV download problem

**Comment by johntruckenbrodt** [comment]
Hi @DTMilodowski I have finally found the time to look into your problem :). I was able to process the image with this:
```Python
from pyroSAR.snap import geocode

filename = 'S1B_IW_GRDH_1SDV_20200730T065341_20200730T065406_022697_02B13D_11A5.zip'
outdir = '/out'

geocode(infile=filename, outdir=outdir, t_srs=4326, tr=50,
        removeS1BorderNoiseMethod='ESA')
```
The error is actually coming from the `Subset` node. For some strange reason its output does not exist. `Subset` writes `*tmp0.dim`, `ThermalNoiseRemoval` `*tmp1.dim` and so on.
Could you please try cloning the latest master? I have made several improvements to the SNAP API and this hopefully fixes it already. If not, could you maybe send me some vector file you are using for the subsetting?
Cheers, John

**Comment by DTMilodowski** [comment]
Thanks @johntruckenbrodt for you lightening-fast response!

I've now got the latest master. I still get this error, before even getting to the subset node:
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='qc.sentinel1.eo.esa.int', port=443): Max retries exceeded with url: /api/v1/?product_type=AUX_POEORB&sentinel1__mission=S1B&validity_start__gte=2020-07-29T06:53:41&validity_stop__lte=2020-07-31T06:53:41 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8516a2f518>, 'Connection to qc.sentinel1.eo.esa.int timed out. (connect timeout=20)'))
`
I thought perhaps this issue had been dealt with, based on scanning pull request #130. I tried deleting my .pyrosar and .snap directories, but this didn't change the above issue.

Any thoughts would be much appreciated.
Cheers,
David

**Comment by DTMilodowski** [comment]
[test_shapefile.zip](https://github.com/johntruckenbrodt/pyroSAR/files/6104077/test_shapefile.zip)
Here is the shapefile being used for the subsetting

**Comment by johntruckenbrodt** [comment]
Yep, unfortunately the issue is not yet resolved. For now you can manually download the needed file here:
https://aux.sentinel1.eo.esa.int/POEORB/2020/08/19/S1B_OPER_AUX_POEORB_OPOD_20200819T111158_V20200729T225942_20200731T005942.EOF, 

zip it into `S1B_OPER_AUX_POEORB_OPOD_20200819T111158_V20200729T225942_20200731T005942.EOF.zip` and store it under `$HOME/.snap/auxdata/Orbits/Sentinel-1/POEORB/S1B/2020/07`.  
This way pyroSAR will just use the local file and not search online.  

I'll later have a look at your processing problem. Thanks for the shapefile.

**Comment by DTMilodowski** [comment]
Great! Thanks for the tip about the manual download

**Comment by DTMilodowski** [comment]
Hi @johntruckenbrodt,
Fantastic. That's much appreciated, and the update is very helpful.
Cheers,
David
