### ISSUE TITLE
`dem_autoload` expired SSL certificate

### ISSUE THREAD

**Issue by maawoo** [johntruckenbrodt/pyroSAR#164]
- which operating system are you using?  
Windows10
- which environment is pyroSAR running in?  
Conda
- which version of pyroSAR are you using?  
Tried in two fresh conda environments with pyroSAR installed via `conda install pyroSAR`
as well as `pip install git+https://github.com/johntruckenbrodt/pyroSAR.git`

-  which function of pyroSAR did you call with which parameters?  

```python
from pyroSAR.auxdata import dem_autoload
from spatialist import Vector

vec_shape = Vector('/../shape.shp')

dem_autoload(geometries=[vec_shape],
             demType='SRTM 1Sec HGT',
             buffer=0.1)
```

- the full error message

```python
Traceback (most recent call last):
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\http\client.py", line 1279, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\http\client.py", line 1325, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\http\client.py", line 1274, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\http\client.py", line 1034, in _send_output
    self.send(msg)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\http\client.py", line 974, in send
    self.connect()
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\http\client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\site-packages\pyroSAR\auxdata.py", line 150, in dem_autoload
    return handler.load(demType=demType,
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\site-packages\pyroSAR\auxdata.py", line 480, in load
    locals = self.__retrieve(self.config[demType]['url'], remotes, outdir)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\site-packages\pyroSAR\auxdata.py", line 322, in __retrieve
    input = urlopen(infile)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\du23yow\Miniconda3\envs\pyrosar1\lib\urllib\request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)>
```

**Comment by johntruckenbrodt** [comment]
Mh interesting. I was not able to reproduce this. Perhaps this might help:
https://medium.com/@yen.hoang.1904/resolve-issue-ssl-certificate-verify-failed-when-trying-to-open-an-url-with-python-on-macos-46d868b44e10

Is ``certifi`` installed? If not we can add it to the ``pyroSAR`` requirements.

```
conda install -c conda-forge certifi
```
