### ISSUE TITLE
encountering FileNotFoundError during parse_node

### ISSUE THREAD

**Issue by rajexp** [johntruckenbrodt/pyroSAR#193]
Getting following error with pyroSAR installation on ubutu OS.
```
/data/anaconda3/envs/datagateway3/snap/bin/../platform/lib/nbexec: WARNING: environment variable DISPLAY is not set
Unrecognized option --dummytest
Traceback (most recent call last):
  File "/data/datagateway/flood.py", line 250, in <module>
    product = read(path_to_sentinel_data, type=process_type)
  File "/data/datagateway/flood.py", line 137, in read
    node = parse_node('Read')
  File "/data/anaconda3/envs/datagatewayx/lib/python3.10/site-packages/pyroSAR/snap/auxil.py", line 86, in parse_node
    version = snap.get_version('s1tbx')['version']
  File "/data/anaconda3/envs/datagatewayx/lib/python3.10/site-packages/pyroSAR/examine.py", line 350, in get_version
    with open(fname, 'r') as m:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.snap/system/var/log/messages.log'
```
I am having following conda installation
```
# packages in environment at /data/anaconda3/envs/datagatewayx:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
affine                    2.3.0                      py_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
anyjson                   0.3.3           pyhd8ed1ab_1004    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h6acc77f_1    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
bcrypt                    3.2.0           py310h6acc77f_2    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
boost-cpp                 1.74.0               h6cacc03_7    conda-forge
boto3                     1.20.50            pyhd8ed1ab_0    conda-forge
botocore                  1.23.50            pyhd8ed1ab_0    conda-forge
branca                    0.4.2              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py310h6acc77f_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.26           h06a4308_2  
cairo                     1.16.0            ha00ac49_1009    conda-forge
certifi                   2021.10.8       py310hff52083_1    conda-forge
cffi                      1.15.0          py310h0fdd8cc_0    conda-forge
cfitsio                   4.0.0                h9a35b8e_0    conda-forge
charset-normalizer        2.0.11             pyhd8ed1ab_0    conda-forge
click                     8.0.3           py310hff52083_1    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
cryptography              36.0.0          py310h9ce1e76_0  
curl                      7.81.0               h2574ce0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              hb2f20db_0  
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.4              pyhd8ed1ab_0    conda-forge
eodag                     2.3.4              pyhd8ed1ab_0    conda-forge
expat                     2.4.4                h9c3ff4c_0    conda-forge
fiona                     1.8.21          py310hfb73927_0    conda-forge
flasgger                  0.9.5              pyhd8ed1ab_1    conda-forge
flask                     2.0.2              pyhd8ed1ab_0    conda-forge
flit-core                 3.6.0              pyhd8ed1ab_0    conda-forge
folium                    0.12.1.post1       pyhd8ed1ab_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.96              ha180cfb_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.29.1          py310h6acc77f_0    conda-forge
freetype                  2.11.0               h70c0345_0  
freexl                    1.0.6                h7f98852_0    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
furl                      2.1.3              pyhd8ed1ab_0    conda-forge
gdal                      3.4.1                    pypi_0    pypi
geoalchemy2               0.9.2              pyhd3eb1b0_0  
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.10.2             pyhd8ed1ab_1    conda-forge
geopandas-base            0.10.2             pyha770c72_1    conda-forge
geos                      3.10.2               h9c3ff4c_0    conda-forge
geotiff                   1.7.0                h6593c0a_6    conda-forge
gettext                   0.21.0               hf68c758_0  
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.70.2               h780b84a_2    conda-forge
glib-tools                2.70.2               h780b84a_2    conda-forge
greenlet                  1.1.2           py310h122e73d_1    conda-forge
gst-plugins-base          1.18.5               hf529b03_3    conda-forge
gstreamer                 1.18.5               h9f60fe5_3    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.12.1          nompi_h2750804_103    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.10.1          py310hff52083_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
infinity                  1.5                pyhd8ed1ab_0    conda-forge
intervals                 0.9.2              pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
jsonpath-ng               1.5.3              pyhd8ed1ab_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
kealib                    1.4.14               h87e4c3c_3    conda-forge
kiwisolver                1.3.2           py310h91b1402_1    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           13_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0           13_linux64_openblas    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libcurl                   7.81.0               h2574ce0_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0  
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgdal                   3.4.1                h7b6f8d3_2    conda-forge
libgfortran-ng            11.2.0              h69a702a_12    conda-forge
libgfortran5              11.2.0              h5c6108e_12    conda-forge
libglib                   2.70.2               h174f98d_2    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libimagequant             2.17.0               h7f98852_1    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0           13_linux64_openblas    conda-forge
libllvm13                 13.0.1               hf817b99_0    conda-forge
libnetcdf                 4.8.1           nompi_hb3fd0d9_101    conda-forge
libnghttp2                1.46.0               h812cca2_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.5                h27cfd23_1  
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     14.1                 hd57d9b9_1    conda-forge
librttopo                 1.1.0                hf69c175_9    conda-forge
libspatialindex           1.9.3                h9c3ff4c_4    conda-forge
libspatialite             5.0.1               h0e567f8_14    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.7                he1b5a44_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libxslt                   1.1.33               h0ef7038_3    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lxml                      4.7.1           py310ha5446b1_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
mapclassify               2.4.3              pyhd8ed1ab_0    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1           py310h6acc77f_1    conda-forge
matplotlib                3.5.1           py310hff52083_0    conda-forge
matplotlib-base           3.5.1           py310h23f4a51_0    conda-forge
mistune                   2.0.2              pyhd8ed1ab_0    conda-forge
multiprocess              0.70.12.2       py310h6acc77f_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mysql-common              8.0.28               ha770c72_0    conda-forge
mysql-libs                8.0.28               hfa10184_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nspr                      4.33                 h295c915_0  
nss                       3.74                 hb5efdd6_0    conda-forge
numpy                     1.22.2          py310h454958d_0    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1m               h7f8727e_0  
orderedmultidict          1.0.1                      py_0    conda-forge
owslib                    0.25.0             pyhd8ed1ab_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.0           py310hb5077e9_0    conda-forge
passlib                   1.7.4              pyh9f0ad1d_0    conda-forge
pathos                    0.2.8              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pendulum                  2.1.2              pyhd8ed1ab_1    conda-forge
phonenumbers              8.12.42            pyhd8ed1ab_0    conda-forge
pillow                    9.0.1           py310h2f95282_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
ply                       3.11                       py_1    conda-forge
poppler                   21.11.0              ha39eefc_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.1                 h2510834_1    conda-forge
pox                       0.3.0              pyhd8ed1ab_0    conda-forge
ppft                      1.6.6.4            pyhd8ed1ab_0    conda-forge
progressbar2              4.0.0              pyhd8ed1ab_0    conda-forge
proj                      8.2.1                h277dcde_0    conda-forge
psycopg2                  2.9.3           py310h6acc77f_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0           py310h9e0d750_1    conda-forge
pyqt                      5.12.3          py310hff52083_8    conda-forge
pyqt-impl                 5.12.3          py310h1f8e252_8    conda-forge
pyqt5-sip                 4.19.18         py310h122e73d_8    conda-forge
pyqtchart                 5.12            py310hfcd6d55_8    conda-forge
pyqtwebengine             5.12.1          py310hfcd6d55_8    conda-forge
pyrosar                   0.15.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1          py310h6acc77f_0    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1           py310hff52083_4    conda-forge
pystac                    1.3.0              pyhd8ed1ab_0    conda-forge
python                    3.10.2          h85951f9_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-utils              3.1.0              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pytzdata                  2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    6.0             py310h6acc77f_3    conda-forge
qt                        5.12.9               ha98a1a1_5    conda-forge
rasterio                  1.2.10          py310h5e0f756_4    conda-forge
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-futures          1.0.0              pyh9f0ad1d_2    conda-forge
rtree                     0.9.7           py310hbdcdc62_3    conda-forge
s3transfer                0.5.1              pyhd8ed1ab_0    conda-forge
scikit-learn              1.0.2           py310h1246948_0    conda-forge
scipy                     1.8.0           py310hea5193d_1    conda-forge
setuptools                60.8.1          py310hff52083_0    conda-forge
setuptools-scm            6.4.2              pyhd8ed1ab_0    conda-forge
setuptools_scm            6.4.2                hd8ed1ab_0    conda-forge
shapely                   1.8.0           py310h1b8dd88_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
spatialist                0.9.0              pyhd8ed1ab_0    conda-forge
sqlalchemy                1.4.31          py310h6acc77f_0    conda-forge
sqlalchemy-utils          0.38.2             pyhd8ed1ab_0    conda-forge
sqlite                    3.37.2               hc218d9a_0  
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.6.2                h2038895_1    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.1             py310h6acc77f_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzcode                    2021e                h7f98852_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0          py310h6acc77f_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
usgs                      0.3.1              pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whoosh                    2.7.4           py310hff52083_5    conda-forge
xerces-c                  3.2.3                h8ce2273_4    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xyzservices               2022.1.1           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

**Comment by johntruckenbrodt** [comment]
Hi @rajexp. The file that pyroSAR reads the SNAP version from is missing:
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/.snap/system/var/log/messages.log'
```

Could you have a look whether this directory exists? If not then it could be that either SNAP is not installed or has never been started yet. This version reading functionality is quite new so it could be that it does not yet work perfectly.

**Comment by johntruckenbrodt** [comment]
I know starting the GUI will create it. This is recommended anyways to occasionally install updates.

**Comment by rajexp** [comment]
@johntruckenbrodt But I have its installation done on non GUI Ubuntu EC2 instance. How does this work there?

**Comment by rajexp** [comment]
@johntruckenbrodt Thanks it appeared after running the command.
