### ISSUE TITLE
Geocode function stopped working: requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by junior-senior** [johntruckenbrodt/pyroSAR#274]
Everything was working fine last week, this week it has been completely broken. I download the .zip files from the Alaskan Satellite Facility and then process them using the Geocode function. This week this error has been occuring when it was completely fine before, I have not made any changes to the code. 

Ubuntu 22.04 GUI and Server
- which environment is pyroSAR running in?  
Virtual Environment
- which version of pyroSAR are you using?  
Install via PIP, version 0.22.2
-  which function of pyroSAR did you call with which parameters? 
-  from pyroSAR.snap.util import geocode
```
geocode(f'{download_save_dir}/{result.properties["fileName"]}',
               out_dir,
               polarizations='all',  # or select 'VV' 'VH'
               shapefile=geojson_vector,
               # can crop out the area of interest (coordinates from the geojson), otherwise put None
               scaling=scale,  # transforms to decibel scale, you can also choose 'linear'
               geocoding_type='Range-Doppler',
               # demName='SRTM 1Sec HGT',
               # which digital elevation model (DEM) to apply in terrain correction, SRTM 1Sec has 30m resolution
               speckleFilter=filter
               # choose a speckle filtering method from 'Boxar', 'Median', 'Frost', 'Gamma Map', 'Refined Lee', 'Lee', 'Lee Sigma'
                            )
```
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
- SNAP UNIX version 9
- the full error message
```
Traceback (most recent call last):
  File "[user file path]/venv/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[user file path]/venv/lib/python3.10/site-packages/pyroSAR/drivers.py", line 1758, in getOSV
    files = osv.catch(sensor=self.sensor, osvtype=osvType,
  File "[user file path]/venv/lib/python3.10/site-packages/pyroSAR/S1/auxil.py", line 421, in catch
    items = self.__catch_gnss(sensor, start, stop, osvtype)
  File "[user file path]/venv/lib/python3.10/site-packages/pyroSAR/S1/auxil.py", line 351, in __catch_gnss
    response_json = response.json()['feed']
  File "[user file path]/venv/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by johntruckenbrodt** [comment]
Thanks for reporting @junior-senior. This happens because the URL for download is no longer available. I have linked a PR which will fix this.
