### ISSUE TITLE
Error when running pyroSAR.snap.geocode

### ISSUE THREAD

**Issue by 1milenac** [johntruckenbrodt/pyroSAR#277]
Hello, I am sorry but this is my first post. I am trying to run geocode on my S1 zip file: 
`
geocode(
            infile='/net/XX/XX/XX/comparison/storage/archive/2022-01-20/S1A_IW_GRDH_1SDV_20220120T163555_20220120T163620_041547_04F0E9_A2D7.SAFE.zip',
            outdir='/net/XX/XX/XX/comparison/storage/archive/2022-01-20',
            spacing=10,
            refarea=["sigma0"],
            demName="SRTM 3Sec",
            polarizations="VV",
            scaling="linear",
            speckleFilter="Lee Sigma",
            demResamplingMethod="BILINEAR_INTERPOLATION",
            imgResamplingMethod="BILINEAR_INTERPOLATION",
            nodataValueAtSea=True,
            allow_RES_OSV=False,
            removeS1ThermalNoise=False,
            removeS1BorderNoise=False,
            terrainFlattening=False,
        )` 
but keep getting the following error: 

Traceback (most recent call last):                                                                                           File "/net/XX/XX/XX/final_env/lib/python3.6/site-packages/requests/models.py", line 910, in json          return complexjson.loads(self.text, **kwargs)                                                                            File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "/net/XX/XX/XX/final_env/lib/python3.6/site-packages/pyroSAR/snap/util.py", line 375, in geocode
    orb = orb_parametrize(scene=id, formatName=formatName, allow_RES_OSV=allow_RES_OSV)
  File "/net/XX/XX/XX/final_env/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 1658, in orb_parametrize
    match = scene.getOSV(osvType=osv_type, returnMatch=True)
  File "/net/XX/XX/XX//final_env/lib/python3.6/site-packages/pyroSAR/drivers.py", line 1754, in getOSV
    url_option=url_option)
  File "/net/XX/XX/XX//final_env/lib/python3.6/site-packages/pyroSAR/S1/auxil.py", line 421, in catch
    items = self.__catch_gnss(sensor, start, stop, osvtype)
  File "/net/XX/XX/XX//final_env/lib/python3.6/site-packages/pyroSAR/S1/auxil.py", line 351, in __catch_gnss
    response_json = response.json()['feed']
  File "/net/XX/XX/XX//final_env/lib/python3.6/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <!doctype html>
<title>The Sentinels Scientific Data Hub</title>
<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
<style>
body { text-align: center; padding: 125px; background: #fff;}
h1 { font-size: 30px; }
body { font: 20px 'Open Sans',Helvetica, sans-serif; color: #333; }
article { display: block; text-align: left; width: 820px; margin: 0 auto; }
a { color: #0062a4; text-decoration: none; font-size: 26px }
a:hover { color: #1b99da; text-decoration: none; }
</style>

<article>
<img alt="" src="/datahub.png" style="float: left;margin: 20px;">
<h1>Copernicus Sentinel Data is now available on the Copernicus Data Space Ecosystem</h1>
<div style="margin-left: 145px;">
<p><a href="https://dataspace.copernicus.eu/">https://dataspace.copernicus.eu</a></p>
</div>

The data was downloaded through  Data Space Copernicus API [link](https://documentation.dataspace.copernicus.eu/APIs/OData.html). Isnt possible to preprocess this data?

I am using Linux ac0736 4.18.0-477.27.1.el8_8.x86_64 and pyroSAR Version: 0.22.1.

**Comment by johntruckenbrodt** [comment]
Hi @1milenac this looks like the problem reported in https://github.com/johntruckenbrodt/pyroSAR/issues/274. Using the latest version 0.23.0 should fix this. Feel free to reopen the issue if necessary.
