### ISSUE TITLE
Support for scenes from CDSE

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#291]
The Copernicus Data Space Ecosystem (CDSE) distributes scenes as COG with a different naming scheme, e.g.:
S1A_IW_GRDH_1SDV_20151021T063752_20151021T063817_008247_00B9CD_2770_COG.SAFE

**Comment by oceanites** [comment]
Another issue I found was that `gdal.Open()` complains about the COG files in the GRDBorderNoiseRemoval step:

```python
Traceback (most recent call last):
  File "/home/tom/venvs/blossom/lib/python3.13/site-packages/pyroSAR/snap/util.py", line 644, in geocode
    gpt(wf_name, groups=groups, cleanup=cleanup, tmpdir=outname,
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        gpt_exceptions=gpt_exceptions, gpt_args=gpt_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        removeS1BorderNoiseMethod=removeS1BorderNoiseMethod)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/venvs/blossom/lib/python3.13/site-packages/pyroSAR/snap/auxil.py", line 411, in gpt
    scene.removeGRDBorderNoise(method=removeS1BorderNoiseMethod)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/venvs/blossom/lib/python3.13/site-packages/pyroSAR/drivers.py", line 1719, in removeGRDBorderNoise
    S1.removeGRDBorderNoise(self, method=method)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/home/tom/venvs/blossom/lib/python3.13/site-packages/pyroSAR/S1/auxil.py", line 758, in removeGRDBorderNoise
    ras_master = gdal.Open(master, GA_Update)
  File "/home/tom/venvs/blossom/lib/python3.13/site-packages/osgeo/gdal.py", line 9239, in Open
    return _gdal.Open(*args)
           ~~~~~~~~~~^^^^^^^
RuntimeError: File /home/tom/scratch/blossom/S1A__IW___D_20230103T052549_Cal_NR_Orb_ML_TF_TC_dB/bnr/S1A_IW_GRDH_1SDV_20230103T052549_20230103T052614_046615_059639_B924_COG.SAFE/measurement/s1a-iw-grd-vv-20230103t052549-20230103t052614-046615-059639-001-cog.tiff has C(loud) O(ptimized) G(eoTIFF) layout. Updating it will generally result in losing part of the optimizations (but will still produce a valid GeoTIFF file). If this is acceptable, open the file with the IGNORE_COG_LAYOUT_BREAK open option set to YES.
```

This can be fixed by changing the code in question to 

```python
ras_master = gdal.OpenEx(master, GA_Update, open_options=["IGNORE_COG_LAYOUT_BREAK=YES"])
ras_slaves = [gdal.OpenEx(x, GA_Update, open_options=["IGNORE_COG_LAYOUT_BREAK=YES"]) for x in scene.findfiles('s1.*tiff') if x != master]
```
