### ISSUE TITLE
name 'isp' is not defined

### ISSUE THREAD

**Issue by maulanarachmat** [johntruckenbrodt/pyroSAR#85]
Hello,
I have installed pyroSAR and trying to process sentinel-1 data with gamma geocode,
I got an error like this : 

> unpacking scene..
> removing border noise..
> border noise removal not necessary for IPF version 2.91
> converting scene to GAMMA format..
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/ubuntusar/anaconda3/envs/envgamma/lib/python3.7/site-packages/pyroSAR/gamma/util.py", line 581, in geocode
>     convert2gamma(scene, scene.scene, logpath=path_log, outdir=scene.scene, shellscript=shellscript)
>   File "/home/ubuntusar/anaconda3/envs/envgamma/lib/python3.7/site-packages/pyroSAR/gamma/util.py", line 269, in convert2gamma
>     isp.par_S1_GRD(**pars)
> NameError: name 'isp' is not defined

I got GAMMA GEO package already installed on my system
How to resolve this, thank you

**Comment by johntruckenbrodt** [comment]
Hi,
pyroSAR makes use of the GAMMA modules DIFF, DISP, ISP and LAT. The command `par_S1_GRD` is part of the ISP package. You would need a GAMMA license including this module. What modules are included in your GEO package?
Regards,
John

**Comment by maulanarachmat** [comment]
It have pretty much cover all command and library for geocoding SAR data, including `par_S1_GRD `as well.
I think its because my GAMMA installation directory only have GEO and DISP so the searching of the commands not defined

**Comment by johntruckenbrodt** [comment]
Ah okay. I didn't know this structure exists. Is this GEO directory organized just like the others with folders  
`./GEO/bin` and `./GEO/scripts` etc.? I could integrate this structure, but it might take some time.

**Comment by maulanarachmat** [comment]
Yes the structure organized like the others folder, thank you
