### ISSUE TITLE
SNAP: execute ThermalNoiseRemoval before SliceAssembly

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#95]
otherwise an error is thrown by SNAP.
The workflow thus needs to first remove noise from each scene and then use the output for the slice assembly. This requires some more complex restructuring of pyroSAR's XML parsing scheme.

**Comment by jeosnes** [comment]
I tried to process Sentinel-1 images with the function geocode for Snap with an external DEM (with the option: externalDEMApplyEGM=False) and SRTM as well. In all those cases I got the same error. I have SNAP 7, Gdal 2.4.2 and latest version of PyroSAR. The error message on the linux server: 

number of scenes:  103
data format not supported
0:00:07.001230
<class 'pyroSAR.drivers.SAFE'>
searching for new POE files
https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_POEORB&sentinel1__mission=S1A&validity_start__gte=2019-01-23T05:25:49&validity_stop__lte=2019-01-25T05:25:49
100% (1 of 1) |#########################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
downloading 1 file
100% (1 of 1) |#########################################################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
deleting 0 RES files
unpacking scene
removing border noise..
border noise removal not necessary for IPF version 2.91
executing node sequences..
Subset
Executing processing graph
 done.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is '/home/software/GDAL-2.4.2/lib:/home/software/GDAL-2.4.2/lib:/home/software/GDAL-2.4.2/lib::/home/GAMMA_SOFTWARE-20181130/lib:/usr/local/lib:/home/GAMMA_SOFTWARE-20181130/lib:/usr/local/lib:/home/GAMMA_SOFTWARE-20181130/lib:/usr/local/lib'.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.URL.openStream(URL.java:1045)
        at org.esa.snap.core.util.VersionChecker.getRemoteVersion(VersionChecker.java:138)
        at org.esa.snap.core.util.VersionChecker.checkForNewRelease(VersionChecker.java:94)
        at org.esa.snap.core.util.EngineVersionCheckActivator.start(EngineVersionCheckActivator.java:21)
        at org.esa.snap.runtime.Engine.informActivators(Engine.java:222)
        at org.esa.snap.runtime.Engine.lambda$start$0(Engine.java:121)
        at org.esa.snap.runtime.Engine.runClientCode(Engine.java:189)
        at org.esa.snap.runtime.Engine.start(Engine.java:121)
        at org.esa.snap.runtime.Engine.start(Engine.java:90)
        at org.esa.snap.runtime.Launcher.run(Launcher.java:51)
        at org.esa.snap.runtime.Launcher.main(Launcher.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
        at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:57)
WARNING: org.esa.snap.core.util.VersionChecker: Not able to check for new SNAP version. Remote version could not be retrieved.

Error: [NodeId: Read] The 'file' parameter is not set

Traceback (most recent call last):
  File "Sentinel1_GRD_geocoding_Snap.py", line 94, in <module>
    geocode(scene, outdir, t_srs = epsg, tr=targetres, polarizations='all', shapefile=shape, scaling=scaling, externalDEMFile=DEMFile, export_extra=['incidenceAngleFromEllipsoid', 'localIncidenceAngle', 'projectedLocalIncidenceAngle', 'DEM'])
  File "/home/vu94riz/.local/lib/python3.6/site-packages/pyroSAR/snap/util.py", line 526, in geocode
    removeS1BorderNoiseMethod=removeS1BorderNoiseMethod)
  File "/home/vu94riz/.local/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 257, in gpt
    execute(sub, cleanup=cleanup, gpt_exceptions=gpt_exceptions)
  File "/home/vu94riz/.local/lib/python3.6/site-packages/pyroSAR/snap/auxil.py", line 163, in execute
    print('failed: {}'.format(os.path.basename(infile)))
  File "/usr/lib64/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by johntruckenbrodt** [comment]
Hi @jeosnes,

thanks a lot for reporting this bug. I am looking into this now. In the future please open a new issue instead of commenting on an existing one so that is is easier for me to keep things organized.
I have also just now added a [contribution guideline](https://github.com/johntruckenbrodt/pyroSAR/blob/master/CONTRIBUTING.md).
This bug was also reported in issue #97 so any further information about it will be posted there.

Regards,
John
