### ISSUE TITLE
SNAP: problems server connection when using external DEM 

### ISSUE THREAD

**Issue by marielaraj** [johntruckenbrodt/pyroSAR#98]
Hi @johntruckenbrodt ,

I attach a problem I am having when I want to use SNAP with an external DEM 👍 

**- which operating system are you using?**  
Ubuntu 18.4.
**- which environment is pyroSAR running in?**  
Python installation.
**- which version of pyroSAR are you using?** 
 0.9.2
**one installed via pip or a clone of the GitHub repository?** 
git clone
**-  which function of pyroSAR did you call with which parameters?**  
We called the following function:
```python
import os
from pyroSAR import identify
from pyroSAR.snap import geocode
from spatialist import Vector
from pyroSAR.auxdata import dem_autoload, dem_create

maindir = '/directory/'

scene = 'img/S1B_IW_GRDH_1SDV_20180317T091416_20180317T091441_010069_01244C_EB9B.zip'
scene = os.path.join(maindir, scene)

bbox = os.path.join(maindir, 'shapefiles/baseshp.shp')
if not os.path.isfile(bbox):
    id = identify(scene)
    id.bbox(bbox)


externaldem = os.path.join(maindir, 'dem.tif')
if not os.path.isfile(externaldem):
    vrt = os.path.join(maindir, 'dem.vrt')
    with Vector(bbox) as site:
        vrt = dem_autoload([site], 'SRTM 1Sec HGT', vrt=vrt)
        dem_create(src=vrt, dst=externaldem,
                   t_srs=32721, tr=(20, 20),
                   resampling_method='bilinear',
                   geoid_convert=True, geoid='EGM96')
    os.remove(vrt)

outdir = os.path.join(maindir, 'proc')

with Vector(bbox) as site:
    wf = geocode(infile=scene, outdir=outdir, t_srs=32721, shapefile=site,
                 removeS1ThermalNoise=False, scaling='db', tr=100,
                 externalDEMFile=externaldem, externalDEMApplyEGM=False,
                 returnWF=True, test=True)
```

Then we modify the xml, we add the applyEGM=false to the first Terrain Correction step and run the new xml (I attach this file) with the gpt comand.

**- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?**
SNAP7
**- the full error message**
[le67hed@geo01 proc]$ gpt S1B__IW___D_20180317T091416_bnr_Orb_Cal_ML_TF_TC_dB_proc.xml
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH does not contain the current folder '.'. Its value is '/home/software/GDAL-2.4.2/lib::/home/software/GAMMA_SOFTWARE-20181130/lib:/usr/local/lib'.
INFO: org.esa.snap.core.util.EngineVersionCheckActivator: Please check regularly for new updates for the best SNAP experience.
Executing processing graph
INFO: org.hsqldb.persist.Logger: dataFileCache open start
version = 2.9
90%INFO: org.esa.snap.engine_utilities.download.DownloadableContentImpl: http retrieving http://step.esa.int/auxdata/dem/egm96/ww15mgh_b.zip
SEVERE: org.esa.snap.engine_utilities.download.DownloadableContentImpl: Failed to download remote file.
java.net.ConnectException: Connection refused (Connection refused)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944)
at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939)
at java.security.AccessController.doPrivileged(Native Method)
at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at org.esa.snap.engine_utilities.download.DownloadableContentImpl.downloadFile(DownloadableContentImpl.java:247)
at org.esa.snap.engine_utilities.download.DownloadableContentImpl.lambda$getRemoteHttpFile$0(DownloadableContentImpl.java:224)
at org.esa.snap.engine_utilities.download.DownloadableContentImpl.getRemoteHttpFile(DownloadableContentImpl.java:229)
at org.esa.snap.dem.dataio.EarthGravitationalModel96.<init>(EarthGravitationalModel96.java:98)
at org.esa.snap.dem.dataio.EarthGravitationalModel96.create(EarthGravitationalModel96.java:85)
at org.esa.snap.dem.dataio.EarthGravitationalModel96.instance(EarthGravitationalModel96.java:77)
at org.esa.snap.dem.dataio.FileElevationTile.<init>(FileElevationTile.java:42)
at org.esa.snap.dem.dataio.FileElevationModel.init(FileElevationModel.java:64)
at org.esa.snap.dem.dataio.FileElevationModel.<init>(FileElevationModel.java:49)
at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.getElevationModel(RangeDopplerGeocodingOp.java:486)
at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.computeTileStack(RangeDopplerGeocodingOp.java:846)
at org.esa.snap.core.gpf.internal.OperatorImageTileStack.computeRect(OperatorImageTileStack.java:116)
at org.esa.snap.core.gpf.internal.OperatorImageTileStack.computeTile(OperatorImageTileStack.java:85)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
at javax.media.jai.OpImage.getTile(OpImage.java:1129)
at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
at com.bc.ceres.glevel.MultiLevelImage.getData(MultiLevelImage.java:64)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:407)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:393)
at org.esa.snap.core.gpf.Operator.getSourceTile(Operator.java:461)
at org.esa.snap.raster.gpf.LinearTodBOp.computeTile(LinearTodBOp.java:116)
at org.esa.snap.core.gpf.internal.OperatorImage.computeRect(OperatorImage.java:80)
at javax.media.jai.SourcelessOpImage.computeTile(SourcelessOpImage.java:137)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
at javax.media.jai.OpImage.getTile(OpImage.java:1129)
at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
at com.bc.ceres.glevel.MultiLevelImage.getData(MultiLevelImage.java:64)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:407)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:393)
at org.esa.snap.core.gpf.internal.OperatorImage.computeRect(OperatorImage.java:73)
at javax.media.jai.SourcelessOpImage.computeTile(SourcelessOpImage.java:137)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
at javax.media.jai.OpImage.getTile(OpImage.java:1129)
at com.sun.media.jai.util.RequestJob.compute(SunTileScheduler.java:247)
at com.sun.media.jai.util.WorkerThread.run(SunTileScheduler.java:468)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
at java.net.PlainSocketImpl.socketConnect(Native Method)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at java.net.Socket.connect(Socket.java:538)
at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
at sun.net.www.http.HttpClient.New(HttpClient.java:339)
at sun.net.www.http.HttpClient.New(HttpClient.java:357)
at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3051)
at java.net.URLConnection.getHeaderFieldLong(URLConnection.java:629)
at java.net.URLConnection.getContentLengthLong(URLConnection.java:501)
at java.net.URLConnection.getContentLength(URLConnection.java:485)
at org.esa.snap.engine_utilities.download.DownloadableContentImpl.downloadFile(DownloadableContentImpl.java:246)
... 34 more

Unable to download http://step.esa.int/auxdata/dem/egm96/ to null
java.lang.NullPointerException
 done.
org.esa.snap.core.gpf.OperatorException: Unable to download http://step.esa.int/auxdata/dem/egm96/ to null
at org.esa.snap.core.gpf.graph.GraphProcessor$GPFImagingListener.errorOccurred(GraphProcessor.java:363)
at com.sun.media.jai.util.SunTileScheduler.sendExceptionToListener(SunTileScheduler.java:1646)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:921)
at javax.media.jai.OpImage.getTile(OpImage.java:1129)
at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
at com.bc.ceres.glevel.MultiLevelImage.getData(MultiLevelImage.java:64)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:407)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:393)
at org.esa.snap.core.gpf.Operator.getSourceTile(Operator.java:461)
at org.esa.snap.raster.gpf.LinearTodBOp.computeTile(LinearTodBOp.java:116)
at org.esa.snap.core.gpf.internal.OperatorImage.computeRect(OperatorImage.java:80)
at javax.media.jai.SourcelessOpImage.computeTile(SourcelessOpImage.java:137)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
at javax.media.jai.OpImage.getTile(OpImage.java:1129)
at javax.media.jai.PlanarImage.getData(PlanarImage.java:2085)
at com.bc.ceres.glevel.MultiLevelImage.getData(MultiLevelImage.java:64)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:407)
at org.esa.snap.core.gpf.internal.OperatorContext.getSourceTile(OperatorContext.java:393)
at org.esa.snap.core.gpf.internal.OperatorImage.computeRect(OperatorImage.java:73)
at javax.media.jai.SourcelessOpImage.computeTile(SourcelessOpImage.java:137)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
at javax.media.jai.OpImage.getTile(OpImage.java:1129)
at com.sun.media.jai.util.RequestJob.compute(SunTileScheduler.java:247)
at com.sun.media.jai.util.WorkerThread.run(SunTileScheduler.java:468)
Caused by: org.esa.snap.core.gpf.OperatorException: Unable to download http://step.esa.int/auxdata/dem/egm96/ to null
at org.esa.snap.engine_utilities.gpf.OperatorUtils.catchOperatorException(OperatorUtils.java:415)
at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.computeTileStack(RangeDopplerGeocodingOp.java:1063)
at org.esa.snap.core.gpf.internal.OperatorImageTileStack.computeRect(OperatorImageTileStack.java:116)
at org.esa.snap.core.gpf.internal.OperatorImageTileStack.computeTile(OperatorImageTileStack.java:85)
at com.sun.media.jai.util.SunTileScheduler.scheduleTile(SunTileScheduler.java:904)
... 21 more
Caused by: org.esa.snap.core.gpf.OperatorException: Unable to download http://step.esa.int/auxdata/dem/egm96/ to null
at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.computeTileStack(RangeDopplerGeocodingOp.java:849)
... 24 more
Caused by: java.io.IOException: Unable to download http://step.esa.int/auxdata/dem/egm96/ to null
at org.esa.snap.dem.dataio.EarthGravitationalModel96.<init>(EarthGravitationalModel96.java:100)
at org.esa.snap.dem.dataio.EarthGravitationalModel96.create(EarthGravitationalModel96.java:85)
at org.esa.snap.dem.dataio.EarthGravitationalModel96.instance(EarthGravitationalModel96.java:77)
at org.esa.snap.dem.dataio.FileElevationTile.<init>(FileElevationTile.java:42)
at org.esa.snap.dem.dataio.FileElevationModel.init(FileElevationModel.java:64)
at org.esa.snap.dem.dataio.FileElevationModel.<init>(FileElevationModel.java:49)
at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.getElevationModel(RangeDopplerGeocodingOp.java:486)
at org.esa.s1tbx.sar.gpf.geometric.RangeDopplerGeocodingOp.computeTileStack(RangeDopplerGeocodingOp.java:846)
... 24 more

Than you,
Mariela.
[S1B__IW___D_20180317T091416_bnr_Orb_Cal_ML_TF_TC_dB_proc.zip](https://github.com/johntruckenbrodt/pyroSAR/files/3869203/S1B__IW___D_20180317T091416_bnr_Orb_Cal_ML_TF_TC_dB_proc.zip)

**Comment by johntruckenbrodt** [comment]
Apparently SNAP still wants some file for the EGM96-WGS84 conversion although we explicitly tell it to not do a conversion. Can you please try the following:
```shell script
cd $HOME/.snap/auxdata/dem/egm96
wget http://step.esa.int/auxdata/dem/egm96/ww15mgh_b.zip
```
This is the file it is trying to download and the only one I have in this directory. The code is working for me so this might fix it.

**Comment by marielaraj** [comment]
Hi @johntruckenbrodt ,

thank you very much, it worked!
Mariela.

**Comment by johntruckenbrodt** [comment]
This file is now downloaded automatically when calling `snap.geocode` via new function `snap.auxil.get_egm96_lookup` (commit d914fe2).
